---
# Configuration file that will be used when generating a new pod from gitpod.io, this also sets up the IDE for further Dev.
image: gitpod/workspace-java-17:2023-05-08-21-16-55

tasks:
  - name: 🛠️ Run app
    command: |
      # ./mvnw clean install -U -DskipTests
      # ./mvnw spring-boot:run

vscode:
  extensions:
    - pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard
