spring:
    datasource:
        url: jdbc:mysql://localhost:3306/aq_prod
        username: aq_prod_user
        password: quazar
    sql:
        init:
            platform: mysql
        
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.MySQLDialect
        database: mysql
        show-sql: false